export default [
  {
    id: 1,
    image: "/HomeProccess/photo1.svg",
    name: "Taxes & Efficiency",
    description: "Business",
    fullImage: "/CaseStudySingleImage/fullImage.svg",
    date: "27th September 2022",
  },
  {
    id: 2,
    image: "/HomeProccess/photo2.svg",
    name: "Planning Guide",
    description: "Hobbies",
    fullImage: "/CaseStudySingleImage/fullImage.svg",
    date: "27th December 2022",
  },
  {
    id: 3,
    image: "/HomeProccess/photo3.svg",
    name: "Investment banking",
    description: "Business",
    fullImage: "/CaseStudySingleImage/fullImage.svg",
    date: "27th December 2022",
  },
  {
    id: 4,
    image: "/HomeProccess/photo4.svg",
    name: "Financial Plan",
    description: "Study",
    fullImage: "/CaseStudySingleImage/fullImage.svg",
    date: "27th July 2022",
  },
  {
    id: 5,
    image: "/HomeProccess/photo5.svg",
    name: "Audit & Evaluation",
    description: "Business",
    fullImage: "/CaseStudySingleImage/fullImage.svg",
    date: "27th August 2022",
  },
  {
    id: 6,
    image: "/HomeProccess/photo6.svg",
    name: "Thematic Study",
    description: "Hobbies",
    fullImage: "/CaseStudySingleImage/fullImage.svg",
    date: "27th June 2022",
  },
];
