import "../node_modules/bootstrap/dist/css/bootstrap-grid.css";
import "./globals.css";
import Header from "./Components/Header";
import Navigation from "./Components/Navigation/index";
import Footer from "./Components/Footer";
import WarningModal from "./Components/WarningModal/index.jsx";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata = {
  title: {
    template: "%s | AskExperts",
    default: "AskExperts",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navigation />
        {children}
        <SpeedInsights />
        <Footer />
        <WarningModal />
      </body>
    </html>
  );
}
