import "../node_modules/bootstrap/dist/css/bootstrap-grid.css";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Navigation from "./Components/Navigation/index";
import Footer from "./Components/Footer";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Navigation />
        {children}
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
