import "../node_modules/bootstrap/dist/css/bootstrap-grid.css";
import "./globals.css";
import Header from "./Components/Header";
import Navigation from "./Components/Navigation/index";
import Footer from "./Components/Footer";
import { Cabin } from "next/font/google";

// const cabin = Cabin({
//   subsets: ["latin"],
//   weight: ["700", "600", "500", "400"],
// });

export const metadata = {
  title: {
    template: "%s | AskExperts",
    default: "AskExperts",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
